db.books.insert([
  {
    title: "The Dune Chronicles",
    genre: "Science Fiction",
    author: "Frank Herbert",
    availableQty: 10,
    read: false,
  },
  {
    title: "I Robot",
    genre: "Science Fiction",
    author: "Isaac Asimov",
    availableQty: 8,
    read: false,
  },
  {
    title: "A Space Odyssey",
    genre: "Science Fiction",
    author: "C. Clarke",
    availableQty: 20,
    read: false,
  },
  {
    title: "The Moon Is A Harsh Mistress",
    genre: "Science Fiction",
    author: "Robert A. Heinlein",
    availableQty: 15,
    read: false,
  },
  {
    title: "Hitler",
    genre: "History",
    author: "Ian Kershaw",
    availableQty: 10,
    read: false,
  },
  {
    title: "1491 - New Revelations of the Americas Before Columbus",
    genre: "History",
    author: "Charles C. Mann",
    availableQty: 10,
    read: false,
  },
  {
    title: "1493: Uncovering the New World Columbus Created",
    genre: "History",
    author: "Charles C. Mann",
    availableQty: 5,
    read: false,
  },
  {
    title: "The Nazi dictatorship",
    genre: "History",
    author: "Ian Kershaw",
    availableQty: 5,
    read: false,
  },
  {
    title: "The Lion, the Witch and the Wardrobe",
    genre: "Fantasy",
    author: "C. S. Lewis",
    availableQty: 8,
    read: false,
  },
  {
    title: "Gardens of the Moon",
    genre: "Fantasy",
    author: "Steven Erikson",
    availableQty: 8,
    read: false,
  },
  {
    title: "Forge of Darkness",
    genre: "Fantasy",
    author: "Steven Erikson",
    availableQty: 18,
    read: false,
  },
  {
    title: "Devil Delivered",
    genre: "Fantasy",
    author: "Steven Erikson",
    availableQty: 18,
    read: false,
  },
  {
    title: "Alexander Hamilton",
    genre: "Biography",
    author: "Ron Chernow",
    availableQty: 10,
    read: false,
  },
  {
    title: "Churchill",
    genre: "Biography",
    author: "Martin Gilbert",
    availableQty: 5,
    read: false,
  },
  {
    title: "In search of Churchill",
    genre: "Biography",
    author: "Martin Gilbert",
    availableQty: 6,
    read: false,
  },
  {
    title: "The Story of Israel",
    genre: "Biography",
    author: "Martin Gilbert",
    availableQty: 7,
    read: false,
  },
]);
